# Generated by Django 5.0.1 on 2024-01-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_main_product_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=30),
        ),
    ]
